version: '3.8'

# Development version with hot reloading
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: code-review-backend-dev
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app:rw
      - ./backend/.env:/app/.env:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - code-review-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: code-review-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    command: npm start
    depends_on:
      - backend
    networks:
      - code-review-network

networks:
  code-review-network:
    driver: bridge